name: Noble Images

on:
  push:
    branches: [main]
    paths: ['Noble/Dockerfile']
  workflow_dispatch:

jobs:
  release:
    name: Release - Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Docker - Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=steam
            type=raw,value=steam-noble
          flavor: latest=true

      - name: Docker - Metadata (Root)
        id: meta_root
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=root
            type=raw,value=root-noble
          flavor: latest=false

      - name: Docker - Build / Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: Noble/Dockerfile
          target: noble
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          
      - name: Docker - Build / Push (Root)
        id: docker_build_root
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: Noble/Dockerfile
          target: noble-root
          push: true
          tags: ${{ steps.meta_root.outputs.tags }}
